### ISSUE TITLE
Add paid tier (umbrella issue)

### ISSUE THREAD

**Issue by apstanisic** [apstanisic/my-subscription#24]
There should be paid tier. For example limit amount of location, number of pictures, number of subscriptions. This feature can also be used to limit app abuse.
Some ideas:

- [x] Limit amount of active subscriptions #25 
- [x] Limit amount of locations #26 
- [x] Limit amount of images #27 
- [x] Limit amount of admins #28 
- [x] Enable logging only for paid users #29

**Comment by apstanisic** [comment]
All issues closed.
